services:
  postgres:
    image: postgres:17
    container_name: msbd-pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dump:/dump
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U msbd"]
      interval: 10s
      retries: 5

  mongo:
    image: mongo:8
    container_name: msbd-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7-alpine
    container_name: msbd-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongodata:
